deployment:
  tasks:
    - export DEPLOYPATH=/home/aihika/public_html/
    - /bin/cp -R * $DEPLOYPATH
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/username/public_html/
#     - /bin/cp -R * $DEPLOYPATH


